{"uuid": "c3f98e98-6f64-4b90-9f4c-82e13a2a479e", "children": ["59a108c8-a3de-4a61-8eac-823e43f56385"], "befores": [{"name": "data_test", "status": "broken", "statusDetails": {"message": "OSError: [Errno 22] Invalid argument: 'C:\\\\Users\\\\Sabri\\\\Documents\\\\AUTOMATION\\\\demo_casino\\\\venv/../data_test/data_C:\\\\Users\\\\Sabri\\\\Documents\\\\AUTOMATION\\\\demo_casino\\\\tests.yaml'\n", "trace": "  File \"C:\\Users\\Sabri\\Documents\\AUTOMATION\\demo_casino\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Sabri\\Documents\\AUTOMATION\\demo_casino\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1121, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Sabri\\Documents\\AUTOMATION\\demo_casino\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 900, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\Sabri\\Documents\\AUTOMATION\\demo_casino\\tests\\conftest.py\", line 9, in data_test\n    return FileUtils.get_yaml_data(f\"{config_location}/data_test/data_{test_filename}.yaml\")\n  File \"C:\\Users\\Sabri\\Documents\\AUTOMATION\\demo_casino\\utilities\\file_utils.py\", line 8, in get_yaml_data\n    with open(file_path, \"r\", encoding='utf-8') as f:\n"}, "start": 1663167682802, "stop": 1663167682802}], "start": 1663167682802, "stop": 1663167684156}